
# Optimisation mémoire production
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

